version: "3.9"
services:
  oracle:
    image: container-registry.oracle.com/database/express:latest
    ports:
      - 1521:1521
      - 5500:5500
    volumes:
      - ./opt/oracle/oradata:/opt/oracle/oradata
    environment:
      - ORACLE_PWD=password
